### ISSUE TITLE
how to import jar in maven project

### ISSUE THREAD

**Issue by fushengss** [gmuth/ipp-client-kotlin#17]
i want to use gradlew scripts to build jar,can you give some example about maven project

**Comment by gmuth** [comment]
https://github.com/gmuth/ipp-samples contain examples using gradle and maven. You need to decide if you build your own projects with gradle or maven.

As for the ipp-client lib build only gradle is supported. However you don't need to build the lib yourself because it is available in [sonatypes maven repo1](https://repo1.maven.org/maven2/de/gmuth/ipp-client/).
