### ISSUE TITLE
IppPrinter#printJob() is sometimes blocking and sometimes not blocking.

### ISSUE THREAD

**Issue by SimonScholz** [gmuth/ipp-client-kotlin#29]
Hi @gmuth ,

thanks again for your investigations and insights in my Pull Request.

I am also sometimes struggling with the problem that calling the `printJob` function is sometimes blocking and sometimes not blocking even though I use the same printer all the time.

Basically this is the code I am using:

```
    override fun printPdfFile(pdfFile: File): PrintJobId {
        require(pdfFile.extension == "pdf") { "Only pdf files are supposed to be passed to this function" }

        val printJob =
            ippPrinter.printJob(
                file = pdfFile,
                DocumentFormat.PDF,
                OrientationRequested.Portrait,
            )

        return PrintJobId(printJob.id)
    }
```

Many times I get back a proper `PrintJobId` almost immediately and sometimes it seems that the `printJob` function call is blocking and kind of never really returns. And despite the fact that it sometimes never returns the printer is still doing it´s job properly and prints everything.

But by extracting the `PrintJobId` I want to actually track the status by asking the `IppPrinter` about the state of a PrintJob by using the  returned `PrintJobId` .
Is there a way to reliably get back a `PrintJobId` when the `printJob` function is called?

**Comment by gmuth** [comment]
The library is using HttpURLConnection which is designed to use blocking calls. So it is expected behavior to wait for the printers response. You can configure the timeout shorter in case you don't accept waiting too long for the printers response. 

`ippPrinter.ippConfig.timeout=Duration.ofSeconds(3)`

What do you mean by "never really returns"? What errors or exceptions do you get?
IPP uses TCP/IP (not UDP) so you should always know when communication is running or breaking (after timeout has passed). You could implement concurrent processing in your application if you don't want to wait for IPP communication to finish.

**Comment by gmuth** [comment]
The issue can most likely be solved by adjusting the current printing workflow. Feel free to contact me by personal mail to arrange commercial support.

**Comment by gmuth** [comment]
To avoid overloading the printer with print jobs:

- Wait for each job to terminate before starting a new job: `ippJob.waitForTermination()`
- Check the printers state before submitting a new job: `ippPrinter.isProcessing()`
  don't forget to refresh the printer-state attributes via ipp:
  `ippPrinter.updateAttributes("printer-state", "printer-state-reasons","printer-state-message")`
