### ISSUE TITLE
HTTP status 426, Need to upgrade, Try ipps://11.22.33.44

### ISSUE THREAD

**Issue by hqyhqyhq** [gmuth/ipp-client-kotlin#31]
W  de.gmuth.ipp.client.HttpPostException: HTTP status 426, Need to upgrade, Try ipps://11.22.33.44
W  	at de.gmuth.ipp.client.IppClient.validateHttpResponse(IppClient.kt:180)
W  	at de.gmuth.ipp.client.IppClient.httpPost(IppClient.kt:113)
W  	at de.gmuth.ipp.client.IppClient.exchange(IppClient.kt:77)
W  	at de.gmuth.ipp.client.CupsClient.exchange(CupsClient.kt:173)
W  	at de.gmuth.ipp.client.CupsClient.addModifyPrinter(CupsClient.kt:98)  
How to solve this problem?

**Comment by hqyhqyhq** [comment]
It seems that SDK API25's reson.
    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            FileAttribute fileAttribute = new FileAttribute() {
                @Override
                public String name() {
                    return null;
                }

                @Override
                public Object value() {
                    return null;
                }
            };
        }
How can I use your maven lib and addModifyPrinter on Android SDK API 25? my microprocessor requirements targetSdk is 25.

**Comment by gmuth** [comment]
Instead of unencrypted ipp/http you need to upgrade to encrypted connections using ipps/https.
Try **ipps://11.22.33.44** instead of ipp://11.22.33.44 as described in the error message.

According to [CUPS operation policies](https://www.cups.org/doc/policies.html) only authenticated system users are allowed for this operation. CUPS requires encrypted connections for authorization.

[Additionally I've added the Upgrade header ](https://github.com/gmuth/ipp-client-kotlin/commit/66b977246a25c0c8bd9b99bebc0223ce590888fa)to the message.
