### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: nio/file/attribute/FileAttribute - Android API Level 25 not supported

### ISSUE THREAD

**Issue by hqyhqyhq** [gmuth/ipp-client-kotlin#32]
It seems that SDK API25's reason.
    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            FileAttribute fileAttribute = new FileAttribute() {
                @Override
                public String name() {
                    return null;
                }

                @Override
                public Object value() {
                    return null;
                }
            };
        }
How can I use your maven lib and addModifyPrinter on Android SDK API 25? my microprocessor requirements targetSdk is 25.

**Comment by gmuth** [comment]
Please provide the full stack trace.

CupsClient does not import from java.nio - so I don't know what code depends on it.
The kotlin-stdlibs should have dependencies to Java. Android API Levels should have dependencies to Java Versions as well. So it could be a kotlin-java-api-level incompatibility. Check build.gradle.kts for current versions.

Which Kotlin and/or Java Version would be required to support Android API Level 25?
You can try the older versions of this library: 2.3, 2.4 or 2.5

[Kotlin 1.7 has been introduced](https://github.com/gmuth/ipp-client-kotlin/commits/master/?since=2022-11-17&until=2022-11-18) after this revision: aa770596f0c5bf4f27565b7c7c724ebdb820f6d1
In order to back port the current source you'd have to look for a solution to createTempDirectory and change probably all java util logging calls because the api now used has been introduced with java 1.8.

Feel free to contact me via personal mail for commercial support.
